src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/GrantBufferFIFO.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/SourceB.scala
to be fully assured that L1 receives Grant before Probe
It is not enough that L2 sends Grant prior to Probe cuz L2 has multiple banks and but L1 only one, and GrantData may still be delayed in xbar
=> SourceB: send Probe after GrantAck received

src/main/scala/coupledL2/MSHR.scala
* For acquireBlock BtoT, L2 should send acquireBlock downwards instead
* of acquirePerm cuz a probe toN may occur during refill process
=> mshr: fix sourceA opcode assignment

src/main/scala/coupledL2/SourceC.scala
sourceC must be FIFO, a case:
L2 Release, then receives Probe and respond ProbeAck NtoN if ProbeAck NtoN were to be sent first in sourceC, then L3 will update client meta as L2 Invalid L3 then receives Release from L2, causing double release assertion failed
=> SourceC: now it is FIFO

src/main/scala/coupledL2/AcquireUnit.scala, src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/GrantBufferFIFO.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MSHRCtl.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/SinkA.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/Slice.scala, src/main/scala/coupledL2/SourceB.scala, src/main/scala/coupledL2/SourceC.scala
The first four have no impact on performance
The last [remove sourceB flow logic](https://github.com/OpenXiangShan/CoupledL2/commit/3504903570f0e8751a70264541b35a063b343e8e) has minor
=> Merge timing fixes to master

src/main/scala/coupledL2/utils/L2PerfCounterUtils.scala
should enable when **!**FPGAPlatform
=> util: fix XSPerfCounters under FPGAPlatform #2

src/main/scala/coupledL2/MSHR.scala
! dirResult.hit  => miss should always write new data OR
gotDirty => when hit and gotDirty, we should also update new data from L3
=>  MSHR: fix bug for dual_core GrantData BtoT dsWen #2

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala
* MSHRInfo: Rename releaseNotSent as blockRefill
* MSHR: Extend 2 cycles for releaseNotSent to block RefillTask in Mainpipe s3 for same cache line
=> MSHR: Fix bug when multiple refill_release in mainpipe not block

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/SinkA.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala
* mshr: add s_retry to label the mshr_task is retry req for way_conflict
* requestArb: use waymask to mask the conflict way for retry mshr_task
* directory & mainpipe: if mshr_task retry, avoid choose the conflict way last time when dir_read
=> Retry wayMask: fix dead lock bug when mshr_refill retry

src/main/scala/coupledL2/CustomL1Hint.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MainPipe.scala
Some deprecated APIs in chisel 3.6.0 have been deleted in chisel 6.0.0-RC2. This PR replaces them.
=> chore: replace deprecated APIs

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala
1. SinkB: cannot accept Probe when same-addr Release to L3 and have not receive ReleaseAck
2. MainPipe: when L3_probetoB and L2=TIP, L2 donot need probetoB L1
3. MSHR: fix bug when L1_acquirePerm but L2_miss, L2 should acquireBlock to L3, not only acquirePerm
4. SinkC: fix bug for regs Buf not init
=> Fix some bugs for CPL2

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala
* SinkC: fix bug for regs Buf not init
* MSHR: fix bug when L1_acquirePerm but L2_miss, L2 should acquireBlock to L3, not only acquirePerm
* MainPipe: when L3_probetoB and L2=TIP, L2 donot need probetoB L1
* SinkB: cannot accept Probe when same-addr Release to L3 and have not receive ReleaseAck
---------
=> Fix some bugs for CPL2 (#99)

src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala, src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
1) LCredit2Decoupled: cannot send credit when reset is asserted
2) LinkLayer: improve readability
=> chi coupledl2 fix bug

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/prefetch/Prefetcher.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
Using hartid from parameters will result in the module not being deduplicated by chisel and firrtl. Each hart will produce its module in verilog, making it hard for the rtl simulator to optimize.
=> configs: use hartid from io

src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2chi/chi/Opcode.scala
According to CHI specification, for non-forwarding snoops, except SnpMakeInvalid, if the RetToSrc value is 1, a copy of the cache line must be returned if the cache line is Shared Clean and the snoopee retains a copy of the cache line.
=> MSHR, MainPipe: return data when non-fwd RetToSrc snoops hit BRANCH

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala
When two snoops are going to probe the same cache line that L2 already sent WriteBackFull but haven't received CompDBIDResp yet, the former snoop will invalidate the block, therefore the latter snoop must not return SnpRespData, cause there is no valid data any more.
=> RXSNP: consider Snp nests a WriteBackFull on an invalid block

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2tl/MSHR.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
Consider a deadlock situation: given 4 ways in each slice, MSHR 0\~3 are accessing separate ways, which makes all the ways occupied. At the same time, MSHR 4 already got CompData from HN, and is waiting for a free way to replace and to echo data through channel D to L1. Therefore MSHR 4 selects replacement way but fails repeatedly. If there is an incoming snoop that has the same address with MSHR 4, the snoop will be blocked because Grant message of MSHR 4 is blocked. Then CompData(s) corresponding to MSHR 0\~3 could not be returned due to the blocked snoop. There goes the deadlock.
This pr breaks the deadlock by restricting the parallelism of L1 demand requests that share the same set to the number of ways.
=> RequestArb: restrict concurrent number of Acquires with same set

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/TopDownMonitor.scala, src/main/scala/coupledL2/debug/Monitor.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala, src/test/scala/TestTop.scala
Before this commit, we use HartIds: Seq[Int] in L2Param. However, it will only contain one element since the code is copied from L3, and L2 is now private to a core, which confuses some developers and causes a bug [1]. To prevent it from happening again, we should use a single HartId here and refactor many of its consumers to use a single HartId.
[1] https://github.com/OpenXiangShan/XiangShan/pull/2966#issuecomment-2105632630
=> configs: use single hartid

src/main/scala/coupledL2/TopDownMonitor.scala
The hartid can be found in what `%m` displays
=> topdown: remove hartid in topdown counter

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala
A transaction size of up to 16-byte is always contained in a single packet. The DataID field value must be set to Addr[5:4] because the DataID field represents Addr[5:4] of the lowest addressed byte within the packet.
=> MMIOBridge: fix bug in DataID and CCID for DAT channels

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/PrefetchParameters.scala, src/main/scala/coupledL2/prefetch/PrefetchReceiver.scala, src/main/scala/coupledL2/prefetch/Prefetcher.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
…disable TP by adding 'hastp/tp' parameter
=> TP: fix compile problem when disable TP by adding 'hastp/tp' parameter

src/main/scala/coupledL2/tl2chi/MainPipe.scala
When a SnpUnique or any other snoops that demands to invalidate all the copies is received, if the snoopee is a dirty TIP but L1 has BRANCH copy, L2 should probe the BRANCH copy in L1.
=> MainPipe: fix bug in the condition of pprobe

src/main/scala/coupledL2/L2Param.scala, src/test/scala/chi/TestTop.scala
* Fixed non-consistent parameter passing of CHI test top
* Changed default TgtId of L2 from 33 to 0 for NoC implementation compatibility (For general cases, the TgtId of HN or NoC components should be specified through the TestTop parameters rather than adopting to the default)
=> TestTop: fixed parameter passing of CHI test top

src/main/scala/coupledL2/SinkC.scala
The beatValids in SinkC is incorrectly invalid, which will cause dataBuf occasionally to be full and cannot accept following Release
=> SinkC: fix the incorrect invalidation of beatValids

src/main/scala/coupledL2/tl2tl/MSHR.scala
This bug will be triggered when the the following events occur in sequence:
* Two client L2s send AcquireBlock BToT for the same target block
* One L2 first obtains T permissions, and another L2 is probed
* L3 sends a probe to the L2 that initially obtained T permission due to a client directory conflict. This probe meets the probeAckThrough condition, causing the dirty block to be written to memory
* L3 responds to the Acquire request from the other L2, retrieves the data from memory, and sends it to that L2 cache.
When the above events occur in sequence, since the directory read happens before Acquire request is sent, the L2 whose request is responded later will assume that it has B permission. Consequently, the granted data will not be written into the dataStorage. When the next …
=> MSHR: fix a dual-core bug when two client L2s send AcquireBlock BToT

.github/CODEOWNERS, src/main/scala/coupledL2/Directory.scala
* To fix the X-state leakage for accurate quad-state simulation
* The original code **SHOULD WORK** without reset in ASIC-only senario
* The original code **SHOULD WORK** without reset in non-quad-state, typically dual-state simulation platform (e.g. verilator)
* The original code **SHOULD WORK** without reset in quad-state simulation platform if SRAMTemplate able to emit randomized data in non-reset state (**not cutting off all X, Z states** in simulation procedure and considering **only the implementation of SRAMTemplate**)
* **The necessity of the reset procedure** of RRIP meta SRAM needed to be disscussed
* **The necessity of the utilization of SRAM** for single-bit RRIP meta 'origin_bit_opt' and other narrow-bit meta fields needed to be discussed
=> Directory: fixed X-state leakage from RRIP meta SRAM without reset

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala
The original address space arrangement might route normal MMIO request into BusErrorUnit. This commit re-arranges address routing so that all the requests in AddressSet(0x0, 0x7fffffff) other than address space of BusErrorUnit will fall into MMIOBridge and access outer NoC/DSU.
=> MMIOBridge: fix address range for MMIO address space

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala
The CCID field must match the value of Addr[5:4] of the original request. For data bus width of 256 bits only the upper order CCID and DataID bits must match.
=> MMIOBridge: fix bug in CCID assignment

src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/utils/Replacer.scala
When Refill, replacerInfo.channel=1, opcode=5 is not Hint, but Grant.
req_type will be used to update RRIP repl_state.
=> Directory: fix bug for req_type

src/main/scala/coupledL2/tl2chi/MSHR.scala
When a SnpOnce hits on a TRUNK block, CoupledL2 will probe upstream cache to acquire the most up-to-date block. When DCache in XiangShan receives Probe toT on a dirty cache line, DCache will echo ProbeAckData TtoT to L2, and erase the dirty flag. Therefore either DCache reserves the dirty flag or L2 marks the block dirty on ProbeAckData TtoT to make sure the dirty data will not be lost. This commit adopts the latter solution.
=> MSHR: fix bug when SnpOnce hits on a TRUNK block

src/main/scala/coupledL2/tl2chi/MSHR.scala
In a snoop DCT transaction, the RN-F provides the read data in CompData that is sent directly to peer RN-F and the DBID must be set to the same value as the TxnID of the snoop.
=> MSHR: fix bug in `DBID` field of CompData with DCT

src/main/scala/coupledL2/tl2chi/MSHR.scala
Before a (TL) Release or (CHI) WriteBackFull/Evict request is sent to TXREQ channel, the request is reponsible for writing the data to be refilled into data storage. From that time on the incoming refill request can continue to choose the same victim way. However in the CHI version, WriteBackFull/Evict might retry after a while and when retry happens we should avoid the task refills data into data storage repeatedly.
Therefore in this commit, WriteBackFull/Evict is sent out towards main pipe the first time with `AllowRetry = 1` in order to refill DS. In the second time it will be sent to TXREQ channel directly with `AllowRetry = 0` to avoid repeated refill.
=> MSHR: fix bug when a retried release writes DS repeatedly

Makefile, scripts/gen_sep_mem.sh, scripts/vlsi_mem_gen, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/utils/BankedSRAM.scala, src/main/scala/coupledL2/utils/SRAMTemplate.scala, src/main/scala/coupledL2/utils/SRAMWrapper.scala
It must satisfy the following requirements:
1. no continuous SRAM reqs (need a gap cycle between two reqs)
2. input signals should hold for at least 2 cycles
3. sample SRAM rdata two cycles after read fire
4. **use enable to clock gate SRAM**, make sure each req is only
sampled once
The process is as follows:
- s0: read fire (enable and input valid)
- s1: input holds, wait for SRAM rdata to be stable
- s2: rdata valid
Here we do not sample/RegEnable rdata in DataStorage, just sending it
out as wire
GrantBuffer will RegEnable it
We set SRAM as external modules during V gen, then use `vlsi_mem_gen` script for SRAM generation.
Such procedure follows that of XiangShan repo.
SRAM in DataStorage uses suggestName to pass MCP2 info to mem-gen script
=> SRAM: implement real MCP2 logic

src/main/scala/coupledL2/RequestBuffer.scala
a. Fixed mergeA and canFlow by qualified by io.in.valid to exclude prefetch
b. The perfermance drop because prefetch request can not allocate buffer
c.  The astar performance verified back to normal IPC=1.78
=> RequestBuffer: Fix performance drop and bug 179

.github/CODEOWNERS, scripts/view_chilog.sh, src/main/scala/coupledL2/tl2chi/chi/CHILogger.scala
for CHILog:
- Log will record every distinct field in CHIREQ, CHIRSP, CHIDAT, CHISNP
- Addresses are saved at TXREQ/RXSNP
- Future responses will use txnID/DBID to match for the corresponding addr
- Support dump every field separately, or just dump the entire flit as UInt
A script `view_chilog.sh` will be used to parse CHILog from db file
```
> ./scripts/view_chilog.sh chiseldb.db -l 16 -w "ADDR=0x18000"
132 L3_L2[0] 18000(98304) TXREQ ReadUnique
132 L3_L2[1] 18000(98304) TXREQ MakeUnique
134 L3_L2[0] 18000(98304) RXSNP SnpMakeInvalid
140 L3_L2[0] 18000(98304) TXRSP SnpResp
142 L3_L2[1] 18000(98304) RXRSP Comp
146 L3_L2[1] 18000(98304) TXRSP CompAck
150 L3_L2[1] 18000(98304) RXSNP SnpUnique
164 L3_L2[1] 18000(98304) TXDAT SnpRespData          5c94b0fed01d7ad4 bdd4b45007188a1b …
```
=> Add CHI-Log

src/main/scala/coupledL2/tl2tl/SinkB.scala
Do not accept Probe when same-addr waiting for ReleaseAck
=> SinkB: fix bug by split the replaceConflict conditions

src/main/scala/coupledL2/tl2chi/MSHR.scala
Each SnpFwd request is allocated an MSHR entry to return SnpResp[Data]Fwded and CompData sequentially. When SnpResp[Data]Fwded reaches stage s3 of MainPipe, it should check whether there are MSHRs with the same addr and write back the latest meta onto the nested MSHR if there is any. If CompData of the origin SnpFwd has not been sent out yet, SnpResp[Data]Fwded might nested write back to itself, which causes the MSHR to stuck on `w_replResp`.
=> MSHR: fix bug when SnpRespFwded nestedwb the same MSHR

src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
An RN-F requests connection to system coherency by setting SYSCOREQ high. The interconnect indicates that coherency is enabled by setting SYSCOACK HIGH.
=> LinkLayer: add system coherency interface

src/main/scala/coupledL2/tl2chi/chi/AsyncBridge.scala
This pull request implements asynchronous bridge on credit-based CHI interface which refers to [AsyncBridgeCHI](https://github.com/cyril0124/NHL2/blob/master/src/main/scala/AsyncBridgeCHI/AsyncBridgeCHI.scala) authored by @cyril0124, but splits the bridge into two parts with different clock domains using [`AsyncQueueSource` and `AsyncQueueSink` in rocket-chip](https://github.com/OpenXiangShan/rocket-chip/blob/e64b744b1490992bd038aaf9ca628f0e29fa0e59/src/main/scala/util/AsyncQueue.scala).
To instantiate the asynchronous bridge, you need to:
1.  instantiate `CHIAsyncBridgeSource` in the clock domain on the upstream side of CHI port,
2. instantiate `CHIAsyncBridgeSink` in the clock domain on the downstream side of CHI port.
=> Add CHI asynchronous bridge

src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/tl2chi/MSHRCtl.scala, src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
In the TL2CHICoupledL2 module, when a PCrdGrant response is received, the corresponding response is directed to a specific slice based on the pArb's chosen signal. `pArb` is an RRArbiter object, and there are uninitialized registers in the RRArbiter. In VCS simulation, these uninitialized registers can lead to an x-state, which propagates to the `chosen` signal, then to the `pCrdSliceID` signal, and eventually to the `ready` signal on the rxrsp channel, causing the simulation to hang.
The solution is to replace the RRArbiter in TL2CHICoupledL2 with RRArbiterInit. This commit also replaces other instances of RRArbiter with RRArbiterInit in CoupledL2
=> Fix the simulation timeout caused by x-state ready signal

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MSHRCtl.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
a. Common:  add pMatch module instance instead of logic for FloorPlan identification
b. MSHR: pCrdGrant handles in next cycle of rxrsp.valid, other operations are in rxrsp.valid cycle 
c. MSHRCtrl: pMatch result registered to fix timing 
d. Slice: add interface to send pMatch result from TL2CHICoupledL2 to MSHRCtrl 
e. TL2CHICoupledL2: handle pWaitInfo residual effetcts because handles pCrdGrant in next cycle of rxrsp.valid
=> TL2CHICoupledL2, MSHR: fix RXRSP timing path

src/main/scala/coupledL2/tl2chi/chi/AsyncBridge.scala, src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
When the asynchronous bridge receives rx\*lcrdv not long after reset, the bridge is not yet ready because the sink part must wait for `ridx` of the source part to be valid in the safe mode. Therefore rx\*lcrdv is lost while the sink part is still not ready. The same is true for tx\*lcrdv in the opposite direction. To fix this bug, this commit sets `tx/rxlinkactivereq` HIGH only when reset process is finish in both source and sink part of the bridge.
=> AsyncBridge: set `tx/rxlinkactivereq` HIGH only when bridge is ready

src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2tl/SourceC.scala, src/main/scala/coupledL2/utils/Queue_SRAM.scala
Queue in `TXDAT/GrantBuffer/Source` are replaced with Queue_SRAM
Since they are large (16×512+), it is area-consuming to build with Reg
=> feat: use dual-port SRAM in Queue for large queues `(TXDAT/GrantBuffer/SourceC)`

src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/utils/BankedSRAM.scala, src/main/scala/coupledL2/utils/SplittedSRAM.scala, src/test/scala/TestSplittedSRAM.scala
split into 4 smaller srams (dataWidth/4)
=> misc: Split Data SRAM in Chisel

src/main/scala/coupledL2/BaseSlice.scala, src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/SinkCMO.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MSHRCtl.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
This PR Remove `RVA23` prefix in code, and fix a wire connecting problem when enable CMO
=> cmo: remove `RVA23` prefix

src/main/scala/coupledL2/tl2chi/chi/AsyncBridge.scala, src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
During reset the following interface signals must be deasserted by the component:
* TX***LCRDV
* TX***FLITV
* TXLINKACTIVEREQ and RXLINKACTIVEACK
The earliest point after reset that it is permitted to begin driving these signals HIGH is at a rising CLK edge after RESETn is HIGH.
=> LinkLayer: During reset RXLINKACTIVEACK must be deasserted

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/prefetch/Prefetcher.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
Bug: TPmetaReq/Resp cannot get fullAddressBits from EdgeIn/OutKey in CoupledL2, since TPmetaReq/Resp are defined in HuanCun(Caused by pr https://github.com/OpenXiangShan/CoupledL2/pull/180)
Solution: use certain parameters for  TPmetaReq/Resp
=> fix(TP): fix XS compiling bug in TPmetaReq/Resp ; submodule(HuanCun): bump HuanCun 

src/main/scala/coupledL2/tl2chi/Bundle.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MSHRCtl.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
This pull request fixes the following possible PCredit related bugs:
1. RetryAck is typically sent by the Completer before PCrdGrant. However, it is permitted to send RetryAck after PCrdGrant. When the latter situation happens, the transaction with credit must only be sent by the Requester after both the RetryAck response and an appropriate PCrdGrant response are received. Before this fix CoupledL2 is unable to handle the latter situation and might drop a PCredit or handle out a PCredit to more than one MSHR.
2. The TxnID field of the PCrdGrant response is not used and must be set to zero. However, before this fix, CoupledL2 hands out all the RXRSP responses, including PCrdGrant, according to the most significant bit in TxnID, which makes MMIOBridge unable to receive PCrdGrant.
This pull …
=> TL2CHICoupledL2: manage PCredits among MMIO and cacheable together

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala, src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
This commit optimizes timing by:
* adding a pipeline stage to update `PCrdValids`
* adding a pipeline stage to arbitrate PCredits to all the slices
* always being ready for RXRSP responses
=> timing(MMIOBridge, TL2CHICoupledL2): optimize PCredit timing

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala
The QoS *Priority Value* for packets is dependent on the source type and the class of traffic with ascending values of QoS indicating a higher priority level. In the previous design QoS is always set to zero, resulting in a rather low use ratio of CMN.
This commit sets all the TXREQ requests with the highest priority to fully utilize the resources in HN-Fs.
=> feat(Common, MSHR): set TXREQ with the highest priority

src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala, src/main/scala/coupledL2/tl2chi/chi/NetworkLayer.scala, src/test/scala/chi/TestTop.scala
This commit introduces a new PCredit management mechanism by:
* implement PCredit pool with simple Queue
* awareness of Home Nodes inside CoupledL2 RN
* seperate PCredit Queue for every Home Node under small-scale
multi-core scenarios
* PCredit dispatch with fast RR arbiter
**NOTICE**: The monolithic approach of PCredit Queue was to be implemented
in the future to better support many cores scenarios with the
area-aware Home-Node-count threshold.
=> timing, area(NetworkLayer, TL2CHICoupledL2): PCredit management

src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala
According to CHI issue E.b spec, the CompAck must only be sent after a CompData or RespSepData is received. In the previous design, if DataSepResp comes before RespSepData, MSHR will send CompAck as long as all the beats of DataSepResp are received which violates the spec.
This commit assigns the status control registers `w_grant`, `w_grantfirst` and `w_grantlast` with new meanings:
* `w_grant`: a CompData or Comp or RespSepData is received
* `w_grantfirst`: a Comp, or the first beat of CompData or DataSepResp is received
* `w_grantlast`: a Comp, or the last beat of CompData or DataSepResp is received
so that CompAck can only be sent when `w_grant` is asserted.
=> fix(MSHR): CompAck must only be sent after CompData or RespSepData

src/main/scala/coupledL2/DataStorage.scala
Since now io.req.valid lasts two cycles,
it shall no longer be used to generate gated clock,
causing double clk for single req.
Instead, we should use io.en now.
=> fix(DataStorage): fix MCP2 gated clock

src/main/scala/coupledL2/tl2chi/MSHR.scala
According to CHI issue E.b spec, the CompAck must only be sent after a CompData or RespSepData is received. It is permitted, but not required, to wait for DataSepResp before sending CompAck. Therefore in the previous design, MSHRs send out a CompAck as soon as a CompData or RespSepData is received, ignoring DataSepResp.
However, the relative ordering of transactions issued by an RN, and snoop transactions caused by transactions from different RNs, is controlled by CompAck. As soon as a CompAck is received, an HN-F is allowed to send a subsequent snoop to the same address. When RN gives a CompAck, this RN is indicating that it will accept responsibility to hazard snoops for any transaction that is scheduled after it. In the previous design CoupledL2 is unable to order snoop after …
=> fix(MSHR): send CompAck only when the first beat of data is received

src/main/scala/coupledL2/tl2chi/MSHR.scala
* 'Get' operations would leave a cache copy with Branch permission in L2 Cache and with no presence of cache line in L1 D-Cache.
* 'SnpRespDataFwded's are permitted to update directory meta for now.
* 'SnpRespDataFwded' with response state of SharedClean does not actually indicate that L1 D-Cache holds the cache line (which might be fetched by non-coherent nodes, e.g. L1 I-Cache, PTW), so on meta update, the client bits of directory meta must be updated with respect to directory read result in addition to the request of invalidating the cache line.
=> fix(MSHR): update client bits with directory result

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/MSHRBuffer.scala, src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/Slice.scala, src/main/scala/coupledL2/utils/HoldChecker.scala
1. In previous design, task_s3_valid_hold2(1) will change during the two cycles,
so it is inproper to use task_s3_valid_hold2.orR as req_valid.
Instead, we just use (0) as req_valid, which is guaranteed to keep unchanged.
3. Add MCP2 Hold Check Assertion in RTL.
Further strengthen the check, which must be asserted during all simulation.
Details at
- https://github.com/OpenXiangShan/CoupledL2/pull/240
=> fix(DataStorage): Fix req_valid and Add MCP2 Check Assertions

src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/chi/Message.scala
* On SnpUniqueFwd, alternative DCT coherency forwarding paths were ```SnpResp_I_Fwded_UC``` and ```SnpResp_I_Fwded_UD_PD```. **And the path of ```SnpRespData_I_PD_Fwded_UC``` was excluded by the CHI specification and illegal on response of SnpUniqueFwd**. The returning data would be directly dumped by Home Node. One another feasible implementation by Home Node was to write the dirty data directly into memory on DCT snoop response, while which was against the original design purpose of DCT and SnpUnique* transactions. Therefore, when the cache line with Unique permission was never written to be turned to dirty, **all dirty data transfered by DCT in transition of ```SnpRespData_I_PD_Fwded_UC``` was lost on the next Evict**.
* Merged some circumstances of snoopee data responding to obtain a …
=> fix(MSHR): excluded illegal DCT path of SnpRespData_I_PD_Fwded_UC

src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2chi/TXREQ.scala, src/main/scala/coupledL2/tl2chi/TXRSP.scala
* For DCT, it was possible for one MSHR to propagate two bundled CHI messages (known for combinations of SnpRespDataFwded with CompData on TXDAT and SnpRespFwded with Comp on TXRSP).
* Assertions for TXDAT, TXREQ and TXRSP of overflowed in-flight tasks.
=> fix(TXDAT, TXRSP): tightened back-pressure of MSHR tasks

Makefile, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/tl2chi/chi/CHILogger.scala, src/test/scala/chi/TestTop.scala
* Use arguments to control generation parameters other than individual App executable classes.
* **CHILogger with flit split is currently broken for Issue E.b**, and to be turned to deprecated, replacing by future support of CHIron CLog.B recording format.
=> chore(TestTop): graceful configuration through arguments

src/main/scala/coupledL2/RequestArb.scala
* Because the CMO tasks go into RequestArb at s1, the MSHR tasks and TileLink Channel Tasks **would not be able to be back-pressured at s0** *( You can't change the past. --TENET :) )*.
* Since CMO tasks would always block the pipelines in cores, so we can assume that CMO tasks were always the newest requests in architectural order, and not causing any significant performance drawback.
=> fix(RequestArb): put CMO at the lowest priority

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/TopDownMonitor.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/PrefetchReceiver.scala, src/main/scala/coupledL2/prefetch/Prefetcher.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
1. fix the bug of prefetch statistics in TopDown
2. fix the bug of vaddr width and the bug of  bestScore initialization (default 0)
3. add some performance debugging means.
1. use constantIn to control the enable signals of `Receiver`, `BOP`, `TP`
2. use constantIn to control part of parameters of `BOP`
3. add ChiselDB to record the prefetch footprints
The point that affects performance is that the initial value of the BOP prefetch score is changed from 10 to 0, which is used for stable initial training. The performance impact results are as follows.
=> fix(l2pf): fix some bugs and add some performance debugging means.

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala, src/main/scala/coupledL2/tl2chi/RXRSP.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2chi/TXRSP.scala
According to CHI issue E.b spec, a component that receives a packet with a TraceTag bit set in every received packet must preserve and reflect the value back in any response packet or spawned packet generated in response to the received packet. This commit specifies the Request-Response pairs that should follow this rule, including:
* A snoop response (including DCT response), with or without data, in response to a snoop request.
* A CompAck from RN in response to CompData, Comp, or RespSepData.
* A write data in response to DBIDResp, DBIDRespOrd, or CompDBIDResp.
=> feat(TL2CHICoupledL2): support TraceTag

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/SinkB.scala
* Never exclude release toB (WriteCleanFull) on nested write back.
* Allow meta write on release toB nested snoops.
=> fix(MSHR, RXSNP): handle nested snoop on WriteCleanFull

.github/workflows/main.yml
In this update, we have changed the GitHub Actions CI runner from ubuntu-latest to ubuntu-22.04 for the following reasons:
- ubuntu-latest currently points to Ubuntu 24.04.
- ubuntu-24.04 is missing the SQLite3 environment, which caused the CI tasks that previously worked to fail.
- Switching to ubuntu-22.04 ensures that the SQLite3 environment is available and functional, resolving this compatibility issue.
see [more details](https://github.com/actions/runner-images/issues/10636).
=> chore(workflow): switch runner to ubuntu-22.04 for CI workflow

src/main/scala/coupledL2/tl2chi/MainPipe.scala
* **```Evict```** derived from ```cbo.inval``` might be nested by snoop from other RNs, and forwarding of nested snoop from ReleaseBuffer should always be available before CMO completion was acknownleged, so data must also be written to ReleaseBuffer when ```cbo.inval``` entered MainPipe on the first time.
* Data should be preserved before CMO completion was acknowledged. Otherwise, the nested snoops were possible to get too-old data, which was not expected under any circumstance, since the data was possible to be excluded from lower-level caches and was transfered between multiple RNs only through multiple DCTs.
=> fix(MainPipe): write ReleaseBuffer on ```cbo.inval```

src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala
* Added user field ```memType_NC``` to recognize **```NC```** type configured by Svpbmt, mapped to *****Non-cacheable Bufferable*****.
* Memory attributes other than **```NC```** are still mapped to *****Device nRnE***** in CHI specification.
=> feat(MMIOBridge): support Svpbmt on CHI MemAttr

src/main/scala/coupledL2/tl2chi/MainPipe.scala
* The ```retry``` and ```need_repl``` signals from the Replacer should be gated by the valid signal of response.
* Hold valid signal of Replacer response in ```s3``` and ```s4``` for MCP2.
=> fix(MainPipe): hold valid of replacer response for MCP2

src/main/scala/coupledL2/tl2chi/MSHR.scala
* Always clear ```meta.clients``` on nested Release.
* Never enable DataStorage write when ```meta.clients``` was absent on Non-to-N Snoop, since the latest data never goes into ReleaseBuffer in this situation.
=> fix(MSHR): reject DS writes on Probe toT nested by Release

src/main/scala/coupledL2/tl2chi/MSHR.scala
* Nested writebacks on replace tasks do not care about directory hit ```dirResult.hit```, since directory was updated early by replacer.
* ```dirResult.hit``` should be take into consideration when it was not a task that might derive replace procedures, for CMO and DCT Forward Snoop.
* **NOTICE**: In old design, it was resumed that missed snoops would not go into MSHR. While, in fact, DCT forward snoops do, for multiple seperate responses. So DCT forward snoops should be excluded from nested writeback logics on directory miss.
=> fix(MSHR): do not nest writeback on missed forward snoop

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2tl/MSHR.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala
* ReleaseBuffer read should not be determined by probeack opcode of SnpResp or SnpRespData.
=> fix(MSHR): moved ReleaseBuffer read determination into MSHR

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2tl/MSHR.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/SinkB.scala
* Never allow ```b_inv_dirty``` (Invalidating WriteBack state inside MSHR by nested Snoops) on SnpStash* and other future snoops that would leave cache lin state untouched.
* Use cache line states in nested MSHR on nested SnpStash* other than that from MainPipe.
=> fix(MainPipe): reject state update on nested SnpStashX

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala
For L2 virtual address training and prefetching, in addition to **TLB miss, uncache, access fault, page fault, and PMP access faults** that have been considered before, **physical memory ranges** also need to be considered. That's what this PR does, adding `PmemRanges` check for virtual address prefetch.
=> fix(BOP): add PmemRanges check for vaddr prefetch

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala
1. revert `PmemRanges` check, because it will be checked in PMA/PMPChecker
[fix(BOP): add PmemRanges check for vaddr prefetch #310](https://github.com/OpenXiangShan/CoupledL2/pull/310)
3. only check `tlbcmd.read` whether a prefetch request needs `Trunk` or not.
**Why not check `tlbcmd.write` when it needs `Trunk`?** 
1. Firstly, you should get why it needs `Trunk`. When there is a prefetch request based on a store train request, we consider it as if it needs write permission (PMA/P level) and further needs unique permission (cache coherence level). So it needs `Trunk`. 
2. Secondly, why not check `tlbcmd.write`. There should know that the prefetch operation only loads the data to L2Cache, not stores any data. Although we predict that it will be write, it only needs to read at this …
=> fix(BOP): only check `tlbcmd.read`

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2chi/chi/Opcode.scala, src/main/scala/coupledL2/tl2tl/MSHR.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/SinkB.scala
This PR, which fixes bugs concerning SnpOnceX-writeback nesting, is based on following table:
| Opcode | Initial State | Final State | RetToSrc | Snoop response | snpHitRelease
| :---: | :---: | :---: | :---: | --- | :---: |
| SnpOnce | I | I | X | SnpResp_I | 0 |
| | UC | UC | X | SnpRespData_UC | 0 |
| | UD | UD | X | SnpRespData_UD | 0 |
| | SC | SC | 0 | SnpResp_SC | 0 |
| | SC | SC | 1 | SnpRespData_SC | 0 |
| SnpOnceFwd | I | I | 0 | SnpResp_I | 0 |
| | UC | UC | 0 | SnpResp_UC_Fwded_I | 0 |
| | UD | UD | 0 | SnpResp_UD_Fwded_I | 0 |
| | SC | SC | 0 | SnpResp_SC_Fwded_I | 0 |
| SnpOnce | I | I | X | SnpResp_I | 1 |
| | UC | I | X | SnpRespData_I | 1 |
| | UD | I | X | SnpRespData_I_PD | 1 |
| | SC | I | 0 | SnpResp_I | 1 |
| | SC | I | 1 | SnpRespData_I | 1 |
| SnpOnceFwd | I | I | …
=> fix(MSHR, MainPipe, RXSNP): fix bugs in SnpOnce*-writeback nesting

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/chi/Message.scala, src/main/scala/coupledL2/tl2chi/chi/Opcode.scala
* For **Issue E.b**, use ```WriteEvictOrEvict``` instead of ```Evict``` on eviction.
* For **Issue B**, we temporarily stay on ```Evict```.
=> feat(MSHR): support WriteEvictOrEvict on eviction

src/main/scala/coupledL2/BaseSlice.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/tl2chi/MSHRCtl.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2tl/MSHRCtl.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
This PR adds the signal of l2Miss and excludes all prefetch.
Whenever there is a L2 miss, the l2miss signal is pulled up.
=> feat(TopDown): add l2Miss IO for Top-Down

src/main/scala/coupledL2/tl2chi/MSHR.scala
The **```TgtID```** of ```CompAck``` for ```WriteEvictOrEvict``` should be propagated from **```SrcID```** of ```Comp```.
=> fix(MSHR): TgtID selection for CompAck of WriteEvictOrEvict

src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/chi/Opcode.scala
This commit supports `SnpQuery`, which is newly supported in Issue E, in CoupledL2.
Brief cache state transitions of `SnpQuery` are as followed:
| Opcode | Initial State | Final State | RetToSrc | Snoop response |
| :---: | :---: | :---: | :---: | :---: |
| SnpQuery| I | I | X | SnpResp_I |
| | UC | UC | 0 | SnpResp_UC |
| | UD | UD | 0 | SnpResp_UD |
| | SC | SC | 0 | SnpResp_SC |
Besides, in Snoopee(L2),  `SnpQuery` must obey following rules:
* Snoop response must not be returned with data
* The state of Snoopee's cache line must not be changed
* `SnpQuery` is only supported in Issue E.b
=> feat(MSHR, MainPipe): support SnpQuery for Issue E.b

src/main/scala/coupledL2/tl2chi/MainPipe.scala
For SnpStash, only the latest copy of the cacheline is needed without changing the state of the cacheline at the snoopee.
Therefore L2 should only send pProbe toT (to get the latest copy) when the state in L2 is TRUNK.
=> fix(MainPipe): SnpStash should probe L1 when L2 cache state is TRUNK

src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
This commit removes critical timing paths from SRAM to ICG, mainly including:
- DataStorage SRAM read result -> error -> regs in BusErrorUnit
- RecentRequestTable SRAM result -> rrTable hit or not -> update ScoreTable
=> timing(Slice, BOP): avoid timing path from SRAM to ICG

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala
* On **```cbo.clean```**, the ```WriteCleanFull``` was determined to be sent only when L1 returned dirty data or L2 contained dirty data.
* Directory meta update was done only by ```mp_release``` on ```WriteCleanFull``` before for CMO operations.
* When L2 contained clean record and L1 returned clean (```ProbeAck TtoB```), ```WriteCleanFull``` was unnecessary. While, the cache line state was still needed to be updated from ```TRUNK``` to ```TIP``` in L2. So ```mp_cmometaw``` was introduced for cache line state update compensation for ```ProbeAck TtoB```.
=> fix(MSHR): always update meta on ProbeAck TtoB under ```cbo.clean```

src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/chi/Opcode.scala
* For **```WriteEvictFull```** and **```WriteEvictOrEvict```**, there is no **silent eviction** path as **```Evict```**. So the initial state of **```WriteEvictFull```** and **```WriteEvictOrEvict```** was never allowed to be ```I```, and the cache state transition must no be done before any WriteData response. Hence, **```WriteEvictFull```** and **```WriteEvictOrEvict```** must be nested by snoops just like **```WriteBackFull```**.
* Distinguishing **```WriteEvictFull```** and **```WriteEvictOrEvict```** from **```WriteBackFull```** for correcting ```PassDirty``` field implementation of nested snoops.
=> fix(MSHR): consider WriteEvict* as nested write back

src/main/scala/coupledL2/tl2chi/MSHR.scala
* Freeze CHI opcode on first release in ```req_released_chiOpcode```, so the opcode would no longer be altered on nesting snoop under retry procedure.
=> fix(MSHR): retry immutability for Release transactions

src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2chi/chi/Message.scala
According to CHI spec, the CCID field must match the value of Addr[5:4] of the original request, and transactions which contain multiple data packets must use the same CCID value for all data packets.
=> fix(TXDAT): fix incorrect assignment of CCID

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala, src/main/scala/coupledL2/tl2chi/TXDAT.scala
This pr fixes bugs concerning `DataCheck`:
* According to the CHI manual, `DataCheck` should use odd parity. Fixed the issue where even parity was incorrectly used in `TXDAT` and `RXDAT`: the parity bit should be obtained by XOR all bits of the data and then XOR the result with 1.
* Should use `VecInit` instead of `Cat` to avoid reverse sequence.
* In `MMIOBridge`, `DataCheck` operations, which are the same as those in `TXDAT` & `RXDAT`, are added for `NC`.
=> fix(TXDAT, RXDAT, MMIOBridge): DataCheck uses odd parity, and support NC

src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/utils/GatedSplittedSRAM.scala
- This is a requirement from DFT,
cause mbist needs to access each sram separately,
and it will do so by adding addtional logic to ClockGate.
- Therefore, ClockGate need also be splitted.
=> feat(DataStorage): split ClockGate for each of the Splitted SRAMs

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala, src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2chi/chi/Message.scala, src/test/scala/chi/TestTop.scala
According to CHI manual, `DataCheck` field should not be present in DAT packet when it's not specified or set to False.
In this pr, 
* In `TestTop`(CHI version), Data Check option is set to `oddparity` as default.
* `enableDataCheck` parameter is moved from `HasCoupledL2Parameters` to `HasCHIMsgParameters`.
* `DataCheck` field in `TXDAT` is defined as Option UInt variable.
When Data Check is enabled, TXDAT/RXDAT/MMIOBridge chooses `oddparity` or `SECDED` accordingly;
otherwise, `DataCheck` filed is `None` in DAT packet.
=> fix(CoupledL2): initialize DataCheck legally

src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala, src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2chi/chi/Message.scala, src/test/scala/TestTop.scala, src/test/scala/chi/TestTop.scala
According to CHI manual, `Poison` field should not be present in DAT packet when it's not specified or set to False.
In this pr, 
* In `TestTop`(CHI version), Poison option is set to `true` as default.
* `enablePoison` parameter is added  to `HasCHIMsgParameters`.
* `Poison` field in `TXDAT` is defined as Option Boolean variable, and its wrong name is fixed.
* `Poison` field is added for UC in MMIOBridge
=> fix(coupledL2): fix Poison init, add Poison for UC

.github/workflows/main.yml, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala
Previous, `MSHR` RXDAT's corrupt does not include `io.resp.rxdat.bits.corrupt`.
Consequently, `DataCheck/Poison` fields in `RXDAT` are not actually used.
In this pr:
* `MSHR` RXDAT's corrupt includes corresponding `DataCheck/Poison`.
* Assertions about `DataCheck/Poison` are added to RXDAT channel.
`DataCheck/Poison` error should not exist in simulation.
=> fix(MSHR): MSHR RXDAT's corrupt includes DataCheck/Poison

src/main/scala/coupledL2/CustomL1Hint.scala
* ```hintQueue``` is now possible to be full and backpressing ```hint_s1Queue```. Hence, overflow assertion for ```hintQueue``` full was unnecessary and overkilled now.
=> fix(CustomL1Hint): removed overkilled assertion

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala
- When DataCheck fails or Poison bits are asserted in CompData, L2 should report `corrupt` to L1. The previous design only considers DataSepResp but omits CompData.
- If there is no slave device in the interconnect to handle the request, error device, for example, will return SLVERR, which is transitioned into Poison in CHI interconnect. Therefore we should not assume that Poison is never asserted. The commit removes assertion check for Poison.
=> fix(MMIOBridge, MSHR): Poison may be asserted

src/main/scala/coupledL2/tl2chi/MSHR.scala
* Since the retry immutability has been guaranteed, the scheduled CopyBackWrData (```s_cbwrdata```) is no longer needed to be updated on writeback retry.
=> fix(MSHR): keep scheduled CopyBackWrData on nested retry

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala
In this pr:
* Modify data name of ECC encode unit in DS.
Previous, `blockBytes` is wrongly used, now replaced by `eccDataBlockBits`
* Parameterize `4` to `eccDataBankSplit`
=> chore(DataStorage): modify data name of ECC encode unit in DS

src/main/scala/coupledL2/tl2chi/MSHR.scala
* Use ```metaChi``` directly for future robustness
=> fix(MSHR): CBWrData with UC/SC on WriteEvictOrEvict

src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala
* Bug description:
SnpQuery response SnpResp_UC instead of SnpResp_I,
when nesting Evict
* Bug fixation:
In MSHR, Evict task sets meta state to INVALID immediately;
* SnpStashX has same problem(fixed together)
=> fix(MSHR): SnpQuery response SnpResp_I on nested Evict

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/RXDAT.scala
* Problem Description:
* DataCheck error detected in L2 cache will not be reported anywhere previously.
* Fixation:
* In MSHR, record  DataCheck error (mp_grant).
* In MainPipe, report detected DataCheck with original ECC error report datapath
* UnCache DataCheck error (in MMIOBridge) will be processed in L1 UC
=> fix(MainPipe, MSHR): report DataCheck error to BEU

src/main/scala/coupledL2/tl2chi/chi/Message.scala
* To support Issue C(specific version), some field width should be changed:
* NodeID Width = 9 bits
* (Physical) Address Width = 44bits
=> fix(Message): support Issue C port(width)

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala
- Seperate `s_compack` of read/dataless and write transactions into two status registers `s_rcompack` and `s_wcompack`
- If the downstream returns a combined data and response (CompData), RN should return CompAck whose TgtID is set to the HomeNID of CompData, and TxnID is set to the DBID of CompData. If the downstream returns a seperate data and response, or return only a response (Comp), RN should return CompAck (if necessary) whose TgtID is set to the SrcID of RespSepData or Comp, and TxnID is set to the DBID of that. In this commit, `srcid`, `homenid` and `dbid` are replaced for better code readability.
=> fix(MSHR): fix bugs of DBID in CompAck of WriteEvictOrEvict

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2tl/MSHR.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/SinkB.scala
**SnpOnceX**: SnpOnce, SnpOnceFwd
**SnpToB**: SnpClean, SnpShared, SnpNotSharedDirty, SnpCleanFwd,
SnpSharedFwd, SnpNotSharedDirtyFwd
* 1) Common: Distinguish WriteBackFull/WriteEvictFull/WriteEvictOrEvict/ Evict nesting from WriteCleanFull using ```snpHitReleaseToInval``` and ```snpHitReleaseToClean``` for better robustness and readability
* 2) MainPipe: For **SnpOnceX** and **SnpToB** nesting WriteCleanFull, redirect cache state to SC
* 3) MainPipe: Update directory meta on **SnpOnceX** nesting WriteCleanFull
* 4) MainPipe: For **SnpCleanShared** nesting WriteCleanFull, allow transition to UC
* 5) MSHR: Clear dirty flag in directory meta on ```mp_probeack``` of **SnpOnceX** nesting WriteCleanFull
* 6) MSHR: For **SnpOnceX** nesting WriteCleanFull, allow PassDirty
=> fix(MainPipe, MSHR): state transitions of nested WriteCleanFull

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/RXSNP.scala, src/main/scala/coupledL2/tl2tl/MSHR.scala
* Before MSHR sends out WriteCleanFull/WriteBackFull/Evict or sends
```cmometaw``` task onto MainPipe, snoop should be **blocked**,
because the snooped block might be performing silent transition of
TRUNK to TIP (UC -> UC).
While, waitings for DS write were unncessary since the silent
transition would only happen on clean block.
=> fix(RXSNP): block RXSNP on CMO ```rprobe``` and ```cmometaw``` task

src/main/scala/coupledL2/BaseSlice.scala, src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/SinkA.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala, src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
* Core initiate flush L2$ all operation by core and L2 interface <io.l2Flush>
* The Barrier is added to wait all mshrs done before l2 flush begin
* The FSM in SinkA is added to insert 'CBO_FLUSH' with set/way task to main pipe
* The set/way are generated by the set loop（0~numSets） and way loop（0~numWays）
* If cache-line is VALID, after CBO flush, main pipe sends back resp to SinkA
* if cache-line is INVALID, main pipe drop it and send back resp to SinkA
* Snoop operations from SinkB is allowed to enter into main pipe
* After all slices done, inform Core and exit coherency
* fix tl2tl version with invalid <io.l2Flush>
* Align code to the coding style
=>  feat(CoupledL2): add flush L2 all operation

src/main/scala/coupledL2/tl2chi/MainPipe.scala
* Consider nested state of INVALID as directory miss, for the possible situation of multiple nesting. Since forwarding logic ```canFwd``` is determined by directory hit. For example, with sequence of:
1. RN sent out WriteBackFull
2. RN received SnpUnique, set nested state to INVALID
3. RN replied SnpResp_I_Fwded_UD_PD with CompData_UD_PD
4. RN received SnpUniqueFwd
5. **RN needed to reply SnpResp_I**
=> fix(MainPipe): nestable directory miss on multiple nesting

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/Consts.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala
* For unified meta reading now on MainPipe, ```dirty``` bits in MSHR were also necessary to be updated on ```mp_probeack``` with clean meta write.
* For better robustness and readability, a new register ```releaseDirty``` is introduced to prevent DataStorage write of ```mp_probeack``` with nested ReleaseData. And, with this change, ProbeAck/ProbeAckData toN from L1 would be allowed on L2 upstream Probe toB.
=> fix(MainPipe, MSHR): update MSHR meta on ProbeAck/ProbeAckData

src/main/scala/coupledL2/tl2chi/MSHR.scala
* SnpOnce always replies SnpRespData_I on UC to I transition, regardless of RetToSrc.
=> fix(MSHR): remove duplicated retToSrc logic of SnpOnce

src/main/scala/coupledL2/tl2chi/MSHR.scala
* Might cause functional problems, while not observed yet. 
* Might cause cache line loss, resulting in unexpected silent eviction.
**The Directory tag writes are protected by MainPipe now, so we will have no functional problems:**
```scala
io.tagWReq.valid := task_s3.valid && req_s3.tagWen && mshr_refill_s3 && !retry
```
=> fix(MSHR): never overwrite directory tags on CBOAck

src/main/scala/coupledL2/tl2chi/MSHR.scala
* On multiple nesting under WriteCleanFull, the cache state may sit at interval state of UC.
* SnpOnceFwd always goes into MSHR as DCT, while SnpOnce nesting WriteCleanFull with TIP would never go into MSHR.
=> fix(MSHR): SnpOnceFwd should reply UC -> UC on UC state

src/main/scala/coupledL2/CoupledL2.scala
* Due to bankBits is 2, 'set' in bank_eq must be 2-bit. but L2DCache Set just 1 bit, so we should use 'tag(LSB) + set(1bit)'.
=> fix(CoupledL2): fix bitwidth in bank_eq

src/main/scala/coupledL2/tl2chi/RXSNP.scala
Assertion is required only if  `rxsnp.valid` = 1.
Otherwise x may be generated in vcs.
=> fix(RXSNP): fix x_value in vcs

src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
Considering the potential unpredictable outcomes when there is L2 memory access after exiting coherence. This fix try to checks whether the Core has entered the WFI (Wait For Interrupt) state. If the Core is already in WFI, it ensures that no further memory accesses will be issued from the Core.
=> fix(TL2CHICoupledL2): add wfi state judgement before exit coherency

src/main/scala/coupledL2/tl2chi/MainPipe.scala
* This would **cause no functional problem**, but against our design purpose. For better I/O ReadOnce performance, data would be always returned on SnpOnce if possible and legal.
=> fix(MainPipe): do SnpRespData on SnpOnce hit UC

src/main/scala/coupledL2/tl2chi/MSHRCtl.scala
1 is a 32-bit signed int by default, and the original coding will cause a negative int when mshrall becomes large.
=> fix(mshr): convert the default SInt to UInt

src/main/scala/coupledL2/tl2chi/MainPipe.scala
* State of WriteCleanFull might be turned to UC on multiple nesting with SnpCleanShared. We only turn UD to SC on SnpOnce nesting WriteCleanFull with state of UD.
=> fix(MainPipe): never turn UC to SC on SnpOnce nesting WriteCleanFull

src/main/scala/coupledL2/tl2chi/MSHR.scala
Currently all write transactions initiated by CBO have the Allocate bit in MemAttr set to zero. However the retry logics do not account for this, resulting in inconsistency of MemAttr between the retry request and the original request.
=> fix(MSHR): fix inconsistency for MemAttr of retry request

src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
* parameterize TP params correctly according to
XS's vaddr/paddr width set
* avoid read and write simultaneously TPMeta SRAM,
which causes false hit
* bump Huancun
=> fix(TemporalPrefetch): parameterize TP params correctly

.github/workflows/main.yml
Old caching APIs were no longer in service due to:
- https://github.com/actions/cache/discussions/1510
We just simply removed cache steps in CI workflow because it never worked as expectation.
=> fix(workflow): remove deprecated cache step

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/Directory.scala
* Set data SRAM(`dataArray` in `DataStorage`) dataSplit = 8.
Previously the dataSplit = 4 and encDataBankBits = 137,
due to area demand, the `dataArray` SRAM bankBits should
be 69. Therefore, after ECC encode, the data need further
split = 2, and add 0 padding(4 bits) each cache line.
* Avoid tag split when tag SRAM's `dataSplit` requirement cannot
be met. This occurs when L2 size changes or `dataSplit` changes
or address width.
* Parameterize Split of tag and data.
=> area(CoupledL2): set data SRAM's dataSplit = 8

src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
By following steps, it can be ensured the process of exit coherency and stop linklayer
a. start exit coherency by syscoreq
b. confirm exiting Coherency completion by syscoack
c. Deassert txsactivereq and comfirm by txsactiveack
d. rxactivereq will be triggered by ICN
e. return L-credit and assert rxactiveack
=> fix(LinkLayer): deactive tx linkactive when exit coherency

src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala
* For NDERR from L3, L2 should not write tag to dir 
in MSHR(mp_grant)
* For denied/corrupt from L1, L2 should update respErr
information if nested in MSHR(mp_cbwrdata)
* For tagErr of L2, L2 should not think that L1 holds 
copy if L1 acquires
* L2 never fwd when tagErr
* For TL-D, always report corrupt if denied is high
* For MMIO, if comp(Write Resp) has DERR, report it as
denied to upstream(corrupt not supported)
=> fix(CoupledL2): supplement tagErr handling

src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
The issue is that the txdat channel's arbiter, when handling a large number of requests, from 4 slices, is unable to respond slice#3 in a timely manner due to the limitations of the fixed-priority scheduling algorithm, considering slice#3 always has the lowest priority, which leads to the commit timeout.
=> fix(TL2CHICoupledL2): fix txrsp and txdat arbiter to RoundRobin

src/main/scala/coupledL2/tl2chi/MSHR.scala
* To meet ISA specification, CMO instructions should only be returned after the consequence was visible to all **non-coherent** agents, which might be out of the CHI domain (e.g. DMAs on crossbars near to memory controller).
=> fix(MSHR): deassert EWA for CMO transactions

src/main/scala/coupledL2/tl2chi/MSHR.scala
* To meet the specification of CHI, EWA must always be asserted on cacheable addresses. There is no Cacheable Non-bufferable memory type from CPU by definition of ARM. And the only choice for CPU interfaces of CHI was to meet the specification, no violation.
* In ISA specification of RISC-V, the CMO order and observability was required to be guaranteed for non-coherent agents, which was impossible for CHI interface scenario. This ridiculous requirement could only be and must be worked-around on NoC level.
=> fix(MSHR): EWA always asserts on cacheable (revert #417)

src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
1. fix syscoreq assert before txsactive asserted when reset is de-asserted.
2. de-asserted txsactive after TX is in TxStop state according to chi protocol 13.7.4
=> fix(Linklayer): fix txsactive asserted before syscoreq after reset

src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
when RN want to exit coherency (syscoreq=0), linkactive should NOT be deasserted before syscoack=0 indicating there is pending snoop on the way, so tx linkactive should keep active until syscoack==0
=> fix(LinkLayer): fix linkactive time when power down

src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
This fix try to fix the false active of 'exitcoDone' the cycle after reset release. So as to resolve the CHI protocal 13.7.2: TXSACTIVE must be asserted when SYSCOREQ is high.
=> fix(LinkLayer): fix exitcoDone signal right after reset

src/main/scala/coupledL2/CoupledL2.scala
Given the new physical-design backend requirements, 
changing the L2 Data SRAM specification to split = 4 is
more favorable for both timing and area.
=> area(DataStorage): change Data SRAM's split to 4
