OpenXiangShan/CoupledL2

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/MSHR.scala
CI passed, https://github.com/OpenXiangShan/XiangShan/pull/2148
=> Fixing bugs

.github/workflows/main.yml, Makefile, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/Slice.scala, src/main/scala/coupledL2/debug/Monitor.scala, src/test/scala/TestTop.scala
in debug/Monitor, dump mainpipe s3 info
=> Add chiselDB

.github/workflows/main.yml, src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/GrantBufferFIFO.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MSHRBuffer.scala, src/main/scala/coupledL2/MSHRCtl.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/RequestBuffer.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/Slice.scala, src/main/scala/coupledL2/SourceC.scala, src/main/scala/coupledL2/TopDownMonitor.scala, src/main/scala/coupledL2/debug/Monitor.scala, src/test/scala/TestTop.scala
choose a replaced way until L2 receives refillData
=> Evict on refill

src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/debug/Monitor.scala, src/main/scala/coupledL2/utils/L2PerfCounterUtils.scala
pass FPGAPlatform param to CPL2 in XSTile 
```chisel
private val l2cache = coreParams.L2CacheParamsOpt.map(l2param =>
LazyModule(new CoupledL2()(new Config((_, _, _) => {
case L2ParamKey => l2param.copy(
hartIds = Seq(p(XSCoreParamsKey).HartId),
FPGAPlatform = debugOpts.FPGAPlatform
)
})))
)
=> chiselDB: fix L2MP exists under FPGAPlatform

src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/L2Param.scala
greatly improve timing
has minor performance decrease
=> timing: revert `divide dir SRAM into N Banks`

src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/SinkB.scala
**Should any future bug occur, we would remove Probe-merge-MSHR-Release**
=> Fix merge probeack

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/SourceB.scala
SourceB: use dcacheSourceIdStart instead of 0.U for source in Probe
=> SourceB: fix source of Probe

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MSHRCtl.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/RequestBuffer.scala, src/main/scala/coupledL2/SinkA.scala, src/main/scala/coupledL2/SinkB.scala, src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/Slice.scala
merge Acquire -> Late Prefetch in MSHR;
remove w_grantack and use inflightgrant idx as sourceD_sink
=> Merge Acquire and Late Prefetch

src/main/scala/coupledL2/MSHR.scala, src/test/scala/TestTop.scala
=> MSHR: fix bug when aliasTask is AcquireBlock NtoT and L2 is Branch 

src/main/scala/coupledL2/MSHR.scala
This reverts commit 201e444bf8a3ea6a0088d5048b0efa134a985069.
=> Revert "MSHR: fix bug for grant meta promotion (#89)"

src/main/scala/coupledL2/CustomL1Hint.scala, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/MSHRBuffer.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/RefillUnit.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/Slice.scala
Already included in kunminghu timing evaluation
=> Fix timing commits into Kunminghu

src/main/scala/coupledL2/CustomL1Hint.scala, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/MSHRBuffer.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/RefillUnit.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/SinkC.scala, src/main/scala/coupledL2/Slice.scala
=> Merge Fix timing Commits into Master

.github/workflows/main.yml, src/main/scala/coupledL2/MSHR.scala, src/main/scala/coupledL2/MainPipe.scala
This should fix bug on dual-core linux kernel bringup
=> Cherry-pick #91 into kunminghu branch

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/CustomL1Hint.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/MainPipe.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/Slice.scala, src/main/scala/coupledL2/SourceC.scala
=> New hint design

src/main/scala/coupledL2/tl2chi/MSHR.scala
When all the ways are occupied with some mshr, other mshrs with the same set may retry to find a way to replace over and over again, which may block the entrance of main pipe and lead to potential deadlock. To resolve the problem, we allow mshr to retry immediately for 3 times (backoffThreshold). If it still fails to find a way, the mshr must back off for a period of time (backoffCycles) to yield the opportunity to access main pipe.
=> MSHR: add backoff time for replace way retry

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala
according to CHI protocal, set allowRetry=0 in retry
=> MSHR: fix allowRetry bit when release retry

Makefile, src/test/scala/chi/TestTop.scala
Fixed test configuration passing glitches due to the currying of the CHI TestTop helpers.
=> TestTop: fixed test configuration passing glitches

src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
* use BigInt for initValue of Constantin.createRecord
=> Bump utility

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/PrefetchParameters.scala, src/main/scala/coupledL2/prefetch/PrefetchReceiver.scala, src/main/scala/coupledL2/prefetch/Prefetcher.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala, src/main/scala/coupledL2/tl2tl/TL2TLCoupledL2.scala, src/test/scala/TestTop.scala
Refactor prefetch param as Seq(BOP, Receiver, TP), so that they are decoupled
https://github.com/OpenXiangShan/XiangShan/pull/2996#issuecomment-2123761099
Performance unchanged for this pr
=> Refactor prefetch param to decouple receiver/bop/tp 

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
trait: HasCoupledL2Parameters and _PrefetcherParams_
so that compilation speed can be faster
=> Parameters: replace val with def in trait 

src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala
update clockgate control in bop.
=> BOP: add clock gating

.github/workflows/main.yml
This commit adds unit test for a dual-core system with CHI-CoupledL2 as RNs and DummyLLC as HN based on tl-test-new.
=> workflows: add unit test for CHI version CoupledL2

src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/RequestBuffer.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/tl2chi/MSHRCtl.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2chi/TXREQ.scala, src/main/scala/coupledL2/tl2chi/TXRSP.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
Timing Fix:
1.noFreeway to RequestBuf
2.fix TXREQ credit
3.disable TX……REQ/TXRSP flow
4.pCredit choose from random to RoundRobin+Timeout protect
5.Remove ICG in BOP
=> CHI-CoupledL2: optimize timing

src/main/scala/coupledL2/tl2chi/MSHR.scala
When a replacement block is nested with a snoop and then needs to retry, MSHR should re-assign `s_cbwrdata` to make sure that no CBWrdata is sent in an Evict transaction.
=> MSHR: fix bug when snoop nests WriteBack before WB retries

src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala
1. change bop entry reset into sync-reset, to optimize fanout
=> fanout: change entry reset into sync-reset

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/RequestBuffer.scala, src/main/scala/coupledL2/SinkA.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/Slice.scala, src/main/scala/coupledL2/tl2tl/MainPipe.scala, src/main/scala/coupledL2/tl2tl/Slice.scala
a. do not check aMerge when prefetch
b. prefetch duplicate with MSHR check move from s1 to s2
c. when prefetch dup MSHR -> drop @S2
=> Seperate SinkA/Prefetch to fix timing

src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala
1. fix the long path of bop `tlb_req` delivery by adding a cycle
2. in SPEC 2006 performance test (0.3 coverage), there is a slight drop, 15.086 -> 15.084 (int 15.186 -> 15.19, fp 15.015 -> 15.009)
=> bop: tlb req adds a cycle for timing

src/main/scala/coupledL2/tl2chi/chi/CHILogger.scala
* adjust the position of the `track()` to fix compilation error
* log address information for DBIDResp and NonCopyBackWrData messages
=> CHILogger: fix bug and support more messages

src/main/scala/coupledL2/tl2chi/MSHRCtl.scala
1. Register of rxrsp may lead to waitPCrdInfo clear 1 cycle late which request credit repeatedly at the next cycle of rxrsp.  
2. Fixed and verified by linux boot succesfully
=> MSHRCtl: fix linux boot by removing register of rxrsp

src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala
replace magic numbers(hardcoding issues) with variable; support sv48(avoid assertion fail)
=> fix(TP): fix hardcoding issues in TP to support sv48

src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/GrantBuffer.scala, src/main/scala/coupledL2/tl2chi/TXDAT.scala, src/main/scala/coupledL2/tl2tl/SourceC.scala
* Split tagArray SRAM in Chisel
* Revert Queue_SRAM to Queue
=> Misc: Split tagArray SRAM & Revert Queue_SRAM

src/main/scala/coupledL2/DataStorage.scala
Should only assert wdata hold condition at WEN (write enable)
=> fix(DataStorage): fix wrong assertion of wdata hold

src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
All address judgements(memory or mmio) are judged in PMA
=> chore(MMIO): Remove addressRange restrictions of memory & mmio

src/main/scala/coupledL2/CoupledL2.scala
* Wrongly connected DecoupledIO ports and ready-valids of CMO dispatch to banks causing the losses of CMO requests.
=> fix(CMO): wrong DecoupledIO dispatch to banks

src/main/scala/coupledL2/tl2chi/TXDAT.scala
According to CHI spec, a requester must deassert all BE values in CopyBackWrData_I and WriteDataCancal packets. Besides, in WriteData and Snoop response Data a byte enable value of zero must set the associated data byte value to zero.
=> fix(TXDAT): fix BE of CopyBackWrData_I

src/main/scala/coupledL2/RequestArb.scala, src/main/scala/coupledL2/tl2chi/MMIOBridge.scala, src/main/scala/coupledL2/tl2chi/MSHR.scala, src/main/scala/coupledL2/tl2chi/MainPipe.scala, src/main/scala/coupledL2/tl2chi/chi/Message.scala, src/main/scala/coupledL2/tl2chi/chi/Opcode.scala
This pull request adds configuration for  CHI Issue C specification.
=> feat: add CHI Issue C

src/main/scala/coupledL2/Common.scala, src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/PrefetchReceiver.scala, src/main/scala/coupledL2/prefetch/Prefetcher.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala, src/test/scala/TestTop.scala, src/test/scala/chi/TestTop.scala
Now add the enable signals for recv, pbop, vbop, tp
=> feat(pf): add prefetch control from core

src/main/scala/coupledL2/RequestArb.scala
=> fix(ReqArbiter): remove impossible condition from channel B

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/Directory.scala
Set tag SRAM dataSplit = 2 in Directory.
Modify tag R/W and tag error logic correspondingly.
=> area(Directory): set tag SRAM data split

src/main/scala/coupledL2/CoupledL2.scala, src/main/scala/coupledL2/DataStorage.scala, src/main/scala/coupledL2/Directory.scala, src/main/scala/coupledL2/L2Param.scala, src/main/scala/coupledL2/prefetch/BestOffsetPrefetch.scala, src/main/scala/coupledL2/prefetch/TemporalPrefetch.scala, src/main/scala/coupledL2/utils/GatedSplittedSRAM.scala, src/main/scala/coupledL2/utils/SplittedSRAM.scala
* add SRAM_CTL interface for CoupledL2
=> feat(SRAM): add sram ctl interface

src/main/scala/coupledL2/tl2chi/TL2CHICoupledL2.scala
define Option IO with hardware attribution of IO
=> fix(TL2CHICoupledL2): define Option IO with hardware attribution of IO

src/main/scala/coupledL2/CoupledL2.scala
=> area(CoupledL2): modify ecc tagBankSpilt

src/main/scala/coupledL2/tl2chi/chi/LinkLayer.scala
This pull request includes the following changes:
1. Sets the maximum L-Credit the receiver can provide on both RXRSP and RXDAT channels to 15.
2. Converts the RXRSP and RXDAT channels to a non-blocking design.
----------
Previously, each RX channel implements a queue matching its L-Credit inflight capacity to temporarily store messages and convert L-Credit handshakes into valid-ready handshakes. However, this approach has two drawbacks:
- It introduces additional area overhead, limiting our ability to scale up the L-Credit inflight capacity due to this area constraint.
- The valid-ready handshake is not timing-friendly.
To address these issues, this pr modifies these two performance-sensitive RX channels (RXRSP and RXDAT) by using counters for tracking inflight L-Credits instead. This …
=> perf, area(LinkLayer): add non-blocking RXDAT and RXRSP
